[tool.poetry]
name = "uk-tax-report"
version = "0.1.0"
description = "UK tax report and capital gains calculator for Portfolio Performance"
authors = ["James Robinson <james.em.robinson@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = ">1.3"
py-moneyed = ">2.0"
python-dateutil = ">2.8"

[tool.poetry.group.dev.dependencies]
black = ">22.0"
flake8 = ">4.0"
isort = ">5.10"
pylint = ">2.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
