name: check-code-style
on: [pull_request]
jobs:
  check-code-style-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Install dependencies
        run: uv sync

      - name: Check imports with ruff
        run: uv run --group dev ruff check --select I --fix .

      - name: Check syntax with ruff
        run: uv run --group dev ruff check .

      - name: Check style with ruff
        run: uv run --group dev ruff format .

